name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      LOG_FORMATTER: brief
      TESTING: "True"
      BLOB_STORAGE_DSN: "fake dsn"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install poetry
      - run: poetry install
      - run: poetry run xenon --no-assert --max-average A --max-modules B --max-absolute B .
      - run: poetry run ruff check .
      - run: poetry run ruff format --check .
      - run: poetry run refurb .
      - run: poetry run mypy .
      - run: poetry run pytest tests --verbose --cov=aquila --cov-report=xml --junitxml=report.xml
